In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [6]:
df = pd.read_csv('processed_data/other_stats.csv')

In [7]:
df['label'].value_counts()

label
good    1632
bad       70
Name: count, dtype: int64

In [8]:
df.shape

(1702, 30)

In [9]:
df.head()

x_Mean     x_Variance  x_Standard Deviation  x_Skewness  x_Kurtosis  \
0 -5.025476  219326.929612            468.323531    0.004672    3.770502   
1 -4.080831  220278.025499            469.337859   -0.001823    3.760244   
2 -5.624304  221917.669106            471.081383    0.020669    3.870206   
3 -4.051225  219635.038250            468.652364   -0.001548    3.759368   
4 -3.874870  220342.925122            469.406993    0.000917    3.768099   

   x_Range  x_Interquartile Range (IQR)  x_Coefficient of Variation  \
0   4012.0                         85.0                  -93.189705   
1   4186.0                        104.0                 -115.010148   
2   4063.0                        114.0                  -83.758007   
3   4227.0                         96.0                 -115.681433   
4   4264.0                        104.0                 -121.141141   

   x_Median Absolute Deviation (MAD)     y_Mean  ...  z_Standard Deviation  \
0                               42.0  32.631773  ...            142.542050   
1                               51.0  34.439658  ...            142.393356   
2                               55.0  30.928157  ...            174.749108   
3                               47.0  32.504339  ...            132.228646   
4                               51.0  34.393633  ...            142.390191   

   z_Skewness  z_Kurtosis  z_Range  z_Interquartile Range (IQR)  \
0    0.080943    0.502954   1347.0                        199.0   
1    0.274388    0.990074   1575.0                        177.0   
2   -0.212467    0.147775   1804.0                        255.0   
3    0.184440    1.051201   1339.0                        162.0   
4    0.279300    1.033053   1634.0                        176.0   

   z_Coefficient of Variation  z_Median Absolute Deviation (MAD)  machine  \
0                   -0.140422                               99.0      M01   
1                   -0.140304                               78.0      M01   
2                   -0.172363                              117.0      M01   
3                   -0.130277                               76.0      M01   
4                   -0.140353                               78.0      M01   

   process_name  label  
0          OP00   good  
1          OP00   good  
2          OP00   good  
3          OP00   good  
4          OP00   good  

[5 rows x 30 columns]

In [10]:
df.describe()

x_Mean     x_Variance  x_Standard Deviation   x_Skewness  \
count  1702.000000    1702.000000           1702.000000  1702.000000   
mean      3.342817  158731.308797            394.689099    -0.119492   
std       6.169227   44592.607525             54.346660     0.174249   
min      -8.565300   62528.172190            250.056338    -0.904509   
25%      -1.335673  124884.154757            353.389515    -0.158090   
50%       1.787200  158943.686216            398.677421    -0.060879   
75%       9.663662  184775.504659            429.855210    -0.014055   
max      24.799726  438045.883760            661.850348     0.459067   

        x_Kurtosis       x_Range  x_Interquartile Range (IQR)  \
count  1702.000000   1702.000000                  1702.000000   
mean      6.722828   4866.690364                   128.631022   
std       2.581408   2162.795419                    73.533662   
min       1.609573   3530.000000                    28.000000   
25%       4.677999   3970.250000                    81.000000   
50%       6.307895   4202.500000                   110.000000   
75%       8.149427   4602.000000                   155.000000   
max      31.278071  17151.000000                   664.000000   

       x_Coefficient of Variation  x_Median Absolute Deviation (MAD)  \
count                 1702.000000                        1702.000000   
mean                    -6.812199                          64.139835   
std                   4364.941608                          36.943115   
min                -108606.437529                          14.000000   
25%                    -99.878836                          41.000000   
50%                     37.922497                          55.000000   
75%                    152.939637                          77.000000   
max                  85791.940504                         332.000000   

            y_Mean  ...  y_Median Absolute Deviation (MAD)       z_Mean  \
count  1702.000000  ...                        1702.000000  1702.000000   
mean     17.375085  ...                          95.279377 -1024.768129   
std      12.854840  ...                          43.218386     8.802327   
min      -3.146913  ...                          27.000000 -1050.753052   
25%       4.274453  ...                          69.000000 -1032.048423   
50%      17.785556  ...                          90.000000 -1021.494456   
75%      30.413069  ...                         109.000000 -1016.142065   
max      90.018052  ...                         485.000000 -1006.618941   

          z_Variance  z_Standard Deviation   z_Skewness   z_Kurtosis  \
count    1702.000000           1702.000000  1702.000000  1702.000000   
mean    41113.823710            194.513138    -0.019968     2.840673   
std     32567.872904             57.274692     0.167401     3.122950   
min      7821.660472             88.440152    -0.873872    -0.920503   
25%     24189.090446            155.528422    -0.079557     0.712021   
50%     33471.976076            182.953480    -0.002878     1.916536   
75%     48563.653582            220.371626     0.061290     4.277914   
max    610983.250000            781.654175     1.222869    28.978974   

           z_Range  z_Interquartile Range (IQR)  z_Coefficient of Variation  \
count  1702.000000                  1702.000000                 1702.000000   
mean   2185.322562                   182.679935                   -0.189792   
std     822.705396                    95.005788                    0.055527   
min     921.000000                    33.000000                   -0.743892   
25%    1634.000000                   119.000000                   -0.214976   
50%    2010.000000                   169.500000                   -0.178962   
75%    2453.000000                   222.000000                   -0.150945   
max    7843.000000                  1114.000000                   -0.085641   

       z_Median Absolute Deviation (MAD)  
count                        1702.000000  
mean 

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1702 entries, 0 to 1701
Data columns (total 30 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   x_Mean                             1702 non-null   float64
 1   x_Variance                         1702 non-null   float64
 2   x_Standard Deviation               1702 non-null   float64
 3   x_Skewness                         1702 non-null   float64
 4   x_Kurtosis                         1702 non-null   float64
 5   x_Range                            1702 non-null   float64
 6   x_Interquartile Range (IQR)        1702 non-null   float64
 7   x_Coefficient of Variation         1702 non-null   float64
 8   x_Median Absolute Deviation (MAD)  1702 non-null   float64
 9   y_Mean                             1702 non-null   float64
 10  y_Variance                         1702 non-null   float64
 11  y_Standard Deviation               1702 non-null   float

In [12]:
df.isnull().sum()

x_Mean                               0
x_Variance                           0
x_Standard Deviation                 0
x_Skewness                           0
x_Kurtosis                           0
x_Range                              0
x_Interquartile Range (IQR)          0
x_Coefficient of Variation           0
x_Median Absolute Deviation (MAD)    0
y_Mean                               0
y_Variance                           0
y_Standard Deviation                 0
y_Skewness                           0
y_Kurtosis                           0
y_Range                              0
y_Interquartile Range (IQR)          0
y_Coefficient of Variation           0
y_Median Absolute Deviation (MAD)    0
z_Mean                               0
z_Variance                           0
z_Standard Deviation                 0
z_Skewness                           0
z_Kurtosis                           0
z_Range                              0
z_Interquartile Range (IQR)          0
z_Coefficient of Variatio

In [13]:
df.label.value_counts()

label
good    1632
bad       70
Name: count, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit label encoder and return encoded labels
df['label'] = label_encoder.fit_transform(df['label'])


df['machine'] = label_encoder.fit_transform(df['machine'])

df['process_name'] = label_encoder.fit_transform(df['process_name'])

In [15]:
df

x_Mean     x_Variance  x_Standard Deviation  x_Skewness  x_Kurtosis  \
0     -5.025476  219326.929612            468.323531    0.004672    3.770502   
1     -4.080831  220278.025499            469.337859   -0.001823    3.760244   
2     -5.624304  221917.669106            471.081383    0.020669    3.870206   
3     -4.051225  219635.038250            468.652364   -0.001548    3.759368   
4     -3.874870  220342.925122            469.406993    0.000917    3.768099   
...         ...            ...                   ...         ...         ...   
1697   9.344506  137312.688755            370.557268    0.039759    9.210417   
1698  10.851487  154256.789720            392.755382    0.093471    7.483669   
1699  12.888480  139978.583084            374.137118   -0.008553    7.805356   
1700  10.101450  133993.363209            366.051039    0.027231    8.498726   
1701  12.764873  137764.055420            371.165806    0.015744    7.829693   

      x_Range  x_Interquartile Range (IQR)  x_Coefficient of Variation  \
0      4012.0                         85.0                  -93.189705   
1      4186.0                        104.0                 -115.010148   
2      4063.0                        114.0                  -83.758007   
3      4227.0                         96.0                 -115.681433   
4      4264.0                        104.0                 -121.141141   
...       ...                          ...                         ...   
1697   4619.0                        122.0                   39.654782   
1698   8478.0                        167.0                   36.193419   
1699   4267.0                         51.0                   29.028569   
1700   4005.0                        118.0                   36.237183   
1701   4096.0                         61.0                   29.076893   

      x_Median Absolute Deviation (MAD)     y_Mean  ...  z_Standard Deviation  \
0                                  42.0  32.631773  ...            142.542050   
1                                  51.0  34.439658  ...            142.393356   
2                                  55.0  30.928157  ...            174.749108   
3                                  47.0  32.504339  ...            132.228646   
4                                  51.0  34.393633  ...            142.390191   
...                                 ...        ...  ...                   ...   
1697                               61.0  18.193375  ...            209.889189   
1698                               83.0  18.011073  ...            201.467115   
1699                               25.0  18.039479  ...            210.055573   
1700                               59.0  19.248543  ...            171.935704   
1701                               31.0  17.816518  ...            219.531564   

      z_Skewness  z_Kurtosis  z_Range  z_Interquartile Range (IQR)  \
0       0.080943    0.502954   1347.0                        199.0   
1       0.274388    0.990074   1575.0                        177.0   
2      -0.212467    0.147775   1804.0                        255.0   
3       0.184440    1.051201   1339.0                        162.0   
4       0.279300    1.033053   1634.0                        176.0   
...          ...         ...      ...                          ...   
1697    0.021756    6.791061   2376.0                         65.0   
1698    0.062642    7.790060   4796.0                         97.0   
1699   -0.010873    6.279592   2448.0                         53.0   
1700   -0.035111    9.535911   2057.0                         78.0   
1701    0.007662    6.608501   2703.0                         61.0   

      z_Coefficient of Variation  z_Median Absolute Deviation (MAD)  machine  \
0                      -0.140422                               99.0        0   
1                      -0.140304                               78.0        0   
2                      -0.172363                              117.0        0   
3                      -0

In [16]:
X = df.drop(['label'], axis=1)
y = df['label']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

### Logistic Regression

In [18]:
# Standardize the features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)

/Users/charanyellanki/Documents/ML/CNC_Machining-main/.venv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
y_pred_lr = model_lr.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_lr)

# Calculate precision
precision = precision_score(y_test, y_pred_lr)

# Calculate recall
recall = recall_score(y_test, y_pred_lr)

# Calculate F1 score
f1 = f1_score(y_test, y_pred_lr)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.9686888454011742
Precision: 0.9778225806451613
Recall: 0.9897959183673469
F1 Score: 0.9837728194726166


In [22]:
print(confusion_matrix(y_test, y_pred_lr))

[[ 10  11]
 [  5 485]]


### Random Forest

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.metrics import accuracy_score

In [24]:
# Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)
rf_pred = rf_model.predict(X_test_scaled)

rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)


print("Random Forest Accuracy:", rf_accuracy)
print("Precision:", rf_precision)
print("Recall:", rf_recall)
print("F1 Score:", rf_f1)

Random Forest Accuracy: 0.9804305283757339
Precision: 0.9838709677419355
Recall: 0.9959183673469387
F1 Score: 0.9898580121703854


In [25]:
print(confusion_matrix(y_test, rf_pred))

[[ 13   8]
 [  2 488]]


In [26]:
# K-Nearest Neighbors (KNN)
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)
knn_pred = knn_model.predict(X_test_scaled)

knn_accuracy = accuracy_score(y_test, knn_pred)
knn_precision = precision_score(y_test, knn_pred)
knn_recall = recall_score(y_test, knn_pred)
knn_f1 = f1_score(y_test, knn_pred)

print("KNN Accuracy:", knn_accuracy)
print("Precision:", knn_precision)
print("Recall:", knn_recall)
print("F1 Score:", knn_f1)


KNN Accuracy: 0.9823874755381604
Precision: 0.9819639278557114
Recall: 1.0
F1 Score: 0.9908998988877654


In [27]:
print(confusion_matrix(y_test, knn_pred))

[[ 12   9]
 [  0 490]]


In [28]:
# Naive Bayes
nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)
nb_pred = nb_model.predict(X_test_scaled)

nb_accuracy = accuracy_score(y_test, nb_pred)
nb_precision = precision_score(y_test, nb_pred)
nb_recall = recall_score(y_test, nb_pred)
nb_f1 = f1_score(y_test, nb_pred)
print("Naive Bayes Accuracy:", nb_accuracy)
print("Precision:", nb_precision)
print("Recall:", nb_recall)
print("F1 Score:", nb_f1)

Naive Bayes Accuracy: 0.9021526418786693
Precision: 0.9910714285714286
Recall: 0.9061224489795918
F1 Score: 0.9466950959488273


In [29]:
print(confusion_matrix(y_test, nb_pred))

[[ 17   4]
 [ 46 444]]


In [30]:
# Support Vector Machine (SVM)
svm_model = SVC(kernel='linear')
svm_model.fit(X_train_scaled, y_train)
svm_pred = svm_model.predict(X_test_scaled)

svm_accuracy = accuracy_score(y_test, svm_pred)
svm_precision = precision_score(y_test, svm_pred)
svm_recall = recall_score(y_test, svm_pred)
svm_f1 = f1_score(y_test, svm_pred)
print("SVM Accuracy:", svm_accuracy)
print("Precision:", svm_precision)
print("Recall:", svm_recall)
print("F1 Score:", svm_f1)

SVM Accuracy: 0.9765166340508806
Precision: 0.9838056680161943
Recall: 0.9918367346938776
F1 Score: 0.9878048780487805


In [31]:
print(confusion_matrix(y_test, svm_pred))

[[ 13   8]
 [  4 486]]


In [32]:
# XGBoost
xgb_model = xgb.XGBClassifier()
xgb_model.fit(X_train_scaled, y_train)
xgb_pred = xgb_model.predict(X_test_scaled)

xg_accuracy = accuracy_score(y_test, xgb_pred)
xg_precision = precision_score(y_test, xgb_pred)
xg_recall = recall_score(y_test, xgb_pred)
xg_f1 = f1_score(y_test, xgb_pred)
print("SVM Accuracy:", xg_accuracy)
print("Precision:", xg_precision)
print("Recall:", xg_recall)
print("F1 Score:", xg_f1)

SVM Accuracy: 0.9823874755381604
Precision: 0.9839034205231388
Recall: 0.9979591836734694
F1 Score: 0.9908814589665653


In [33]:
print(confusion_matrix(y_test, xgb_pred))

[[ 13   8]
 [  1 489]]
