In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('processed_data/tsfresh.csv')

In [3]:
df.shape

(1702, 14097)

In [4]:
df.head()

min_x__variance_larger_than_standard_deviation  min_x__has_duplicate_max  \
0                                             0.0                       0.0   
1                                             0.0                       0.0   
2                                             0.0                       0.0   
3                                             0.0                       0.0   
4                                             0.0                       0.0   

   min_x__has_duplicate_min  min_x__has_duplicate  min_x__sum_values  \
0                       0.0                   0.0            -2012.0   
1                       0.0                   0.0            -1940.0   
2                       0.0                   0.0            -2260.0   
3                       0.0                   0.0            -2022.0   
4                       0.0                   0.0            -2008.0   

   min_x__abs_energy  min_x__mean_abs_change  min_x__mean_change  \
0          4048144.0                   128.0               -74.0   
1          3763600.0                   128.0               -74.0   
2          5107600.0                   128.0               -74.0   
3          4088484.0                   128.0               -74.0   
4          4032064.0                   128.0               -74.0   

   min_x__mean_second_derivative_central  min_x__median  ...  \
0                                    0.0        -2012.0  ...   
1                                    0.0        -1940.0  ...   
2                                    0.0        -2260.0  ...   
3                                    0.0        -2022.0  ...   
4                                    0.0        -2008.0  ...   

   mean_z__permutation_entropy__dimension_3__tau_1  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   

   mean_z__permutation_entropy__dimension_4__tau_1  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   

   mean_z__permutation_entropy__dimension_5__tau_1  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   

   mean_z__permutation_entropy__dimension_6__tau_1  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   

   mean_z__permutation_entropy__dimension_7__tau_1  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   

   mean_z__query_similarity_count__query_None__threshold_0.0  \
0                                                0.0           
1                                                0.0           
2                                                0.0           
3                                                0.0           
4                                                0.0           

   mean_z__mean_n_absolute_max__number_of_maxima_7  machine  process_name  \
0                                              0.0        0             0   
1                                              0.0        0             0   
2                                              0.0        0 

In [5]:
df.describe()

min_x__variance_larger_than_standard_deviation  \
count                                     1702.000000   
mean                                         0.070505   
std                                          0.256072   
min                                          0.000000   
25%                                          0.000000   
50%                                          0.000000   
75%                                          0.000000   
max                                          1.000000   

       min_x__has_duplicate_max  min_x__has_duplicate_min  \
count                    1702.0                    1702.0   
mean                        0.0                       0.0   
std                         0.0                       0.0   
min                         0.0                       0.0   
25%                         0.0                       0.0   
50%                         0.0                       0.0   
75%                         0.0                       0.0   
max                         0.0                       0.0   

       min_x__has_duplicate  min_x__sum_values  min_x__abs_energy  \
count                1702.0        1702.000000       1.702000e+03   
mean                    0.0       -2595.916569       7.723349e+06   
std                     0.0        1305.106041       1.051939e+07   
min                     0.0       -9250.000000       3.031081e+06   
25%                     0.0       -2459.000000       3.755844e+06   
50%                     0.0       -2059.000000       4.239481e+06   
75%                     0.0       -1938.000000       6.005475e+06   
max                     0.0       -1741.000000       8.526676e+07   

       min_x__mean_abs_change  min_x__mean_change  \
count             1702.000000         1702.000000   
mean               143.626322          -63.649824   
std                212.273667          226.969187   
min                  2.000000         -960.000000   
25%                128.000000          -74.000000   
50%                128.000000          -74.000000   
75%                128.000000          -74.000000   
max               4401.000000         4401.000000   

       min_x__mean_second_derivative_central  min_x__median  ...  \
count                                 1702.0    1702.000000  ...   
mean                                     0.0   -2437.506463  ...   
std                                      0.0    1177.292919  ...   
min                                      0.0   -9234.000000  ...   
25%                                      0.0   -2269.500000  ...   
50%                                      0.0   -2035.000000  ...   
75%                                      0.0   -1932.000000  ...   
max                                      0.0   -1732.000000  ...   

       mean_z__permutation_entropy__dimension_3__tau_1  \
count                                           1702.0   
mean                                               0.0   
std                                                0.0   
min                                                0.0   
25%                                                0.0   
50%                                                0.0   
75%                                                0.0   
max                                                0.0   

       mean_z__permutation_entropy__dimension_4__tau_1  \
count                                           1702.0   
mean                                               0.0   
std                                                0.0   
min                                                0.0   
25%                                                0.0   
50%                                                0.0   
75%                                                0.0   
max                                                0.0   

       mean_z__permutation_entropy__dimension_5__tau_1  \
count                                           1702.0   
mean                                               0.0   
std       

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1702 entries, 0 to 1701
Columns: 14097 entries, min_x__variance_larger_than_standard_deviation to label
dtypes: float64(14094), int64(3)
memory usage: 183.1 MB


In [7]:
df.isnull().sum()

min_x__variance_larger_than_standard_deviation               0
min_x__has_duplicate_max                                     0
min_x__has_duplicate_min                                     0
min_x__has_duplicate                                         0
min_x__sum_values                                            0
                                                            ..
mean_z__query_similarity_count__query_None__threshold_0.0    0
mean_z__mean_n_absolute_max__number_of_maxima_7              0
machine                                                      0
process_name                                                 0
label                                                        0
Length: 14097, dtype: int64

In [8]:
df.label.value_counts()

label
1    1632
0      70
Name: count, dtype: int64

In [9]:
df

min_x__variance_larger_than_standard_deviation  \
0                                                0.0   
1                                                0.0   
2                                                0.0   
3                                                0.0   
4                                                0.0   
...                                              ...   
1697                                             0.0   
1698                                             0.0   
1699                                             0.0   
1700                                             0.0   
1701                                             0.0   

      min_x__has_duplicate_max  min_x__has_duplicate_min  \
0                          0.0                       0.0   
1                          0.0                       0.0   
2                          0.0                       0.0   
3                          0.0                       0.0   
4                          0.0                       0.0   
...                        ...                       ...   
1697                       0.0                       0.0   
1698                       0.0                       0.0   
1699                       0.0                       0.0   
1700                       0.0                       0.0   
1701                       0.0                       0.0   

      min_x__has_duplicate  min_x__sum_values  min_x__abs_energy  \
0                      0.0            -2012.0          4048144.0   
1                      0.0            -1940.0          3763600.0   
2                      0.0            -2260.0          5107600.0   
3                      0.0            -2022.0          4088484.0   
4                      0.0            -2008.0          4032064.0   
...                    ...                ...                ...   
1697                   0.0            -2619.0          6859161.0   
1698                   0.0            -2832.0          8020224.0   
1699                   0.0            -2471.0          6105841.0   
1700                   0.0            -2250.0          5062500.0   
1701                   0.0            -2295.0          5267025.0   

      min_x__mean_abs_change  min_x__mean_change  \
0                      128.0               -74.0   
1                      128.0               -74.0   
2                      128.0               -74.0   
3                      128.0               -74.0   
4                      128.0               -74.0   
...                      ...                 ...   
1697                   128.0               -74.0   
1698                   128.0               -74.0   
1699                   128.0               -74.0   
1700                   128.0               -74.0   
1701                   128.0               -74.0   

      min_x__mean_second_derivative_central  min_x__median  ...  \
0                                       0.0        -2012.0  ...   
1                                       0.0        -1940.0  ...   
2                                       0.0        -2260.0  ...   
3                                       0.0        -2022.0  ...   
4                                       0.0        -2008.0  ...   
...                                     ...            ...  ...   
1697                                    0.0        -2619.0  ...   
1698                                    0.0        -2832.0  ...   
1699                                    0.0        -2471.0  ...   
1700                                    0.0        -2250.0  ...   
1701                                    0.0        -2295.0  ...   

      mean_z__permutation_entropy__dimension_3__tau_1  \
0                                                 0.0   
1                                                 0.0   
2                                                 0.0   
3                                                 0.0   
4                                                 0.0   
...                    

In [10]:
X = df.drop(['label'], axis=1)
y = df['label']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

### Logistic Regression

In [12]:
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)

/Users/charanyellanki/Documents/ML/CNC_Machining-main/.venv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
y_pred_lr = model_lr.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_lr)

# Calculate precision
precision = precision_score(y_test, y_pred_lr)

# Calculate recall
recall = recall_score(y_test, y_pred_lr)

# Calculate F1 score
f1 = f1_score(y_test, y_pred_lr)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.9510763209393346
Precision: 0.9546351084812623
Recall: 0.9958847736625515
F1 Score: 0.9748237663645518


In [15]:
print(confusion_matrix(y_test, y_pred_lr))

[[  2  23]
 [  2 484]]


### Random Forest

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.metrics import accuracy_score

In [17]:
# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
# Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)
rf_pred = rf_model.predict(X_test_scaled)

rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)


print("Random Forest Accuracy:", rf_accuracy)
print("Precision:", rf_precision)
print("Recall:", rf_recall)
print("F1 Score:", rf_f1)

Random Forest Accuracy: 0.9315068493150684
Precision: 0.9574036511156186
Recall: 0.9711934156378601
F1 Score: 0.9642492339121552


In [19]:
print(confusion_matrix(y_test, rf_pred))

[[  4  21]
 [ 14 472]]


In [20]:
# K-Nearest Neighbors (KNN)
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)
knn_pred = knn_model.predict(X_test_scaled)

knn_accuracy = accuracy_score(y_test, knn_pred)
knn_precision = precision_score(y_test, knn_pred)
knn_recall = recall_score(y_test, knn_pred)
knn_f1 = f1_score(y_test, knn_pred)

print("KNN Accuracy:", knn_accuracy)
print("Precision:", knn_precision)
print("Recall:", knn_recall)
print("F1 Score:", knn_f1)


KNN Accuracy: 0.9354207436399217
Precision: 0.9594320486815415
Recall: 0.9732510288065843
F1 Score: 0.9662921348314607


In [21]:
print(confusion_matrix(y_test, knn_pred))

[[  5  20]
 [ 13 473]]


In [22]:
# Naive Bayes
nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)
nb_pred = nb_model.predict(X_test_scaled)

nb_accuracy = accuracy_score(y_test, nb_pred)
nb_precision = precision_score(y_test, nb_pred)
nb_recall = recall_score(y_test, nb_pred)
nb_f1 = f1_score(y_test, nb_pred)
print("Naive Bayes Accuracy:", nb_accuracy)
print("Precision:", nb_precision)
print("Recall:", nb_recall)
print("F1 Score:", nb_f1)

Naive Bayes Accuracy: 0.9452054794520548
Precision: 0.9770833333333333
Recall: 0.9650205761316872
F1 Score: 0.9710144927536232


In [23]:
print(confusion_matrix(y_test, nb_pred))

[[ 14  11]
 [ 17 469]]


In [24]:
# Support Vector Machine (SVM)
svm_model = SVC(kernel='linear')
svm_model.fit(X_train_scaled, y_train)
svm_pred = svm_model.predict(X_test_scaled)

svm_accuracy = accuracy_score(y_test, svm_pred)
svm_precision = precision_score(y_test, svm_pred)
svm_recall = recall_score(y_test, svm_pred)
svm_f1 = f1_score(y_test, svm_pred)
print("SVM Accuracy:", svm_accuracy)
print("Precision:", svm_precision)
print("Recall:", svm_recall)
print("F1 Score:", svm_f1)

SVM Accuracy: 0.9354207436399217
Precision: 0.9575757575757575
Recall: 0.9753086419753086
F1 Score: 0.9663608562691132


In [25]:
print(confusion_matrix(y_test, svm_pred))

[[  4  21]
 [ 12 474]]


In [26]:
# XGBoost
xgb_model = xgb.XGBClassifier()
xgb_model.fit(X_train_scaled, y_train)
xgb_pred = xgb_model.predict(X_test_scaled)

xg_accuracy = accuracy_score(y_test, xgb_pred)
xg_precision = precision_score(y_test, xgb_pred)
xg_recall = recall_score(y_test, xgb_pred)
xg_f1 = f1_score(y_test, xgb_pred)
print("SVM Accuracy:", xg_accuracy)
print("Precision:", xg_precision)
print("Recall:", xg_recall)
print("F1 Score:", xg_f1)

SVM Accuracy: 0.9315068493150684
Precision: 0.9574036511156186
Recall: 0.9711934156378601
F1 Score: 0.9642492339121552


In [27]:
print(confusion_matrix(y_test, xgb_pred))

[[  4  21]
 [ 14 472]]
