In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
df = pd.read_csv('processed_data/five_summary.csv')

In [4]:
df.shape

(1702, 21)

In [5]:
df.head()

min_x  min_y  min_z  25%_x   25%_y     25%_z   50%_x  50%_y  50%_z  75%_x  \
0 -2008.0  -50.0   -9.0   35.0  2004.0 -5.025476 -1774.0  -39.0   39.0   91.0   
1 -1940.0  -58.0   -9.0   46.0  2246.0 -4.080831 -1887.0  -50.0   27.0  126.0   
2 -2039.0  -64.0  -11.0   50.0  2024.0 -5.624304 -1973.0  -44.0   31.0  103.0   
3 -2006.0  -56.0   -7.0   40.0  2221.0 -4.051225 -1870.0  -35.0   37.0   87.0   
4 -2012.0  -58.0   -9.0   46.0  2252.0 -3.874870 -1868.0  -54.0   27.0  128.0   

   ...      75%_z   max_x   max_y   max_z  mean_x  mean_y       mean_z  \
0  ...  32.631773 -1663.0 -1116.0 -1015.0  -917.0  -316.0 -1015.094961   
1  ...  34.439658 -1795.0 -1098.0 -1036.0  -921.0  -220.0 -1014.888903   
2  ...  30.928157 -2106.0 -1149.0  -989.0  -894.0  -302.0 -1013.841030   
3  ...  32.504339 -1651.0 -1093.0 -1028.0  -931.0  -312.0 -1014.980279   
4  ...  34.393633 -1786.0 -1097.0 -1036.0  -921.0  -152.0 -1014.514865   

   machine process_name label  
0      M01         OP00  good  
1      M01         OP00  good  
2      M01         OP00  good  
3      M01         OP00  good  
4      M01         OP00  good  

[5 rows x 21 columns]

In [6]:
df.describe()

min_x        min_y        min_z        25%_x        25%_y  \
count  1702.000000  1702.000000  1702.000000  1702.000000  1702.000000   
mean  -2437.506463   -60.481199     5.974736    68.149824  2429.183901   
std    1182.640763    34.290203    10.345186    40.489773   998.567597   
min   -9234.000000  -335.000000   -13.000000     9.000000  1731.000000   
25%   -2269.500000   -70.000000     0.000000    40.000000  2002.500000   
50%   -2035.000000   -56.000000     7.000000    56.000000  2155.000000   
75%   -1932.000000   -40.000000    15.000000    87.000000  2347.500000   
max   -1698.000000    -5.000000    23.000000   329.000000  8657.000000   

             25%_z        50%_x        50%_y        50%_z        75%_x  \
count  1702.000000  1702.000000  1702.000000  1702.000000  1702.000000   
mean      3.342817 -1800.032902   -78.159518    15.525852   113.195358   
std       6.169227   752.930319    45.740928     9.935961    44.926312   
min      -8.565300 -6552.000000  -464.000000   -29.000000    37.000000   
25%      -1.335673 -2185.500000  -100.500000     7.000000    83.000000   
50%       1.787200 -1758.000000   -70.000000    15.000000   111.000000   
75%       9.663662 -1180.500000   -48.000000    23.000000   132.000000   
max      24.799726  -622.000000     5.000000    54.000000   501.500000   

             75%_y        75%_z        max_x        max_y        max_z  \
count  1702.000000  1702.000000  1702.000000  1702.000000  1702.000000   
mean   1834.537603    17.375085 -2148.157462 -1116.730611 -1025.007051   
std     805.724107    12.854840   431.508082    49.997341    12.160109   
min     618.000000    -3.146913 -4753.000000 -1598.000000 -1085.000000   
25%    1179.250000     4.274453 -2339.000000 -1136.000000 -1032.000000   
50%    1789.000000    17.785556 -2057.000000 -1110.000000 -1024.000000   
75%    2204.000000    30.413069 -1836.500000 -1085.000000 -1018.000000   
max    6023.000000    90.018052 -1497.000000 -1030.000000  -970.000000   

            mean_x       mean_y       mean_z  
count  1702.000000  1702.000000  1702.000000  
mean   -934.050676    37.165100 -1024.768129  
std      46.723390   430.301274     8.802327  
min   -1024.000000  -599.000000 -1050.753052  
25%    -966.000000  -234.000000 -1032.048423  
50%    -942.000000   -52.000000 -1021.494456  
75%    -911.000000   133.500000 -1016.142065  
max    -484.000000  3090.000000 -1006.618941

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1702 entries, 0 to 1701
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   min_x         1702 non-null   float64
 1   min_y         1702 non-null   float64
 2   min_z         1702 non-null   float64
 3   25%_x         1702 non-null   float64
 4   25%_y         1702 non-null   float64
 5   25%_z         1702 non-null   float64
 6   50%_x         1702 non-null   float64
 7   50%_y         1702 non-null   float64
 8   50%_z         1702 non-null   float64
 9   75%_x         1702 non-null   float64
 10  75%_y         1702 non-null   float64
 11  75%_z         1702 non-null   float64
 12  max_x         1702 non-null   float64
 13  max_y         1702 non-null   float64
 14  max_z         1702 non-null   float64
 15  mean_x        1702 non-null   float64
 16  mean_y        1702 non-null   float64
 17  mean_z        1702 non-null   float64
 18  machine       1702 non-null 

In [8]:
df.isnull().sum()

min_x           0
min_y           0
min_z           0
25%_x           0
25%_y           0
25%_z           0
50%_x           0
50%_y           0
50%_z           0
75%_x           0
75%_y           0
75%_z           0
max_x           0
max_y           0
max_z           0
mean_x          0
mean_y          0
mean_z          0
machine         0
process_name    0
label           0
dtype: int64

In [9]:
df.label.value_counts()

label
good    1632
bad       70
Name: count, dtype: int64

In [10]:
df[df['machine'] == 'M01']['process_name'].value_counts()

process_name
OP07    47
OP02    46
OP13    43
OP01    40
OP05    38
OP12    37
OP04    36
OP09    36
OP08    34
OP10    33
OP00    29
OP03    28
OP14    28
OP06    23
OP11    21
Name: count, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit label encoder and return encoded labels
df['label'] = label_encoder.fit_transform(df['label'])


df['machine'] = label_encoder.fit_transform(df['machine'])

df['process_name'] = label_encoder.fit_transform(df['process_name'])

In [12]:
df

min_x  min_y  min_z  25%_x   25%_y      25%_z   50%_x  50%_y  50%_z  \
0    -2008.0  -50.0   -9.0   35.0  2004.0  -5.025476 -1774.0  -39.0   39.0   
1    -1940.0  -58.0   -9.0   46.0  2246.0  -4.080831 -1887.0  -50.0   27.0   
2    -2039.0  -64.0  -11.0   50.0  2024.0  -5.624304 -1973.0  -44.0   31.0   
3    -2006.0  -56.0   -7.0   40.0  2221.0  -4.051225 -1870.0  -35.0   37.0   
4    -2012.0  -58.0   -9.0   46.0  2252.0  -3.874870 -1868.0  -54.0   27.0   
...      ...    ...    ...    ...     ...        ...     ...    ...    ...   
1697 -2295.0  -52.0   15.0   70.0  2324.0   9.344506 -2764.0  -58.0   17.0   
1698 -4475.0  -76.0   19.0   91.0  4003.0  10.851487 -2996.0  -39.0   17.0   
1699 -1950.0  -11.0   17.0   40.0  2317.0  12.888480 -2010.0  -25.0   17.0   
1700 -1979.0  -50.0   15.0   68.0  2026.0  10.101450 -1606.0  -48.0   17.0   
1701 -1897.0  -17.0   17.0   44.0  2199.0  12.764873 -2006.0  -25.0   17.0   

      75%_x  ...      75%_z   max_x   max_y   max_z  mean_x  mean_y  \
0      91.0  ...  32.631773 -1663.0 -1116.0 -1015.0  -917.0  -316.0   
1     126.0  ...  34.439658 -1795.0 -1098.0 -1036.0  -921.0  -220.0   
2     103.0  ...  30.928157 -2106.0 -1149.0  -989.0  -894.0  -302.0   
3      87.0  ...  32.504339 -1651.0 -1093.0 -1028.0  -931.0  -312.0   
4     128.0  ...  34.393633 -1786.0 -1097.0 -1036.0  -921.0  -152.0   
...     ...  ...        ...     ...     ...     ...     ...     ...   
1697   99.0  ...  18.193375 -2209.0 -1054.0 -1022.0  -989.0   167.0   
1698   80.0  ...  18.011073 -3822.0 -1069.0 -1020.0  -972.0   974.0   
1699   64.5  ...  18.039479 -2201.0 -1048.0 -1020.0  -995.0   247.0   
1700   89.0  ...  19.248543 -2127.0 -1059.0 -1022.0  -981.0   -70.0   
1701   66.0  ...  17.816518 -2344.0 -1050.0 -1020.0  -989.0   359.0   

           mean_z  machine  process_name  label  
0    -1015.094961        0             0      1  
1    -1014.888903        0             0      1  
2    -1013.841030        0             0      1  
3    -1014.980279        0             0      1  
4    -1014.514865        0             0      1  
...           ...      ...           ...    ...  
1697 -1022.487604        2            13      1  
1698 -1019.704778        2            13      1  
1699 -1020.280482        2            13      1  
1700 -1020.916288        2            13      1  
1701 -1020.236168        2            13      1  

[1702 rows x 21 columns]

In [13]:
X = df.drop(['label'], axis=1)
y = df['label']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

### Logistic Regression

In [15]:
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)

/Users/charanyellanki/Documents/ML/CNC_Machining-main/.venv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
y_pred_lr = model_lr.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_lr)

# Calculate precision
precision = precision_score(y_test, y_pred_lr)

# Calculate recall
recall = recall_score(y_test, y_pred_lr)

# Calculate F1 score
f1 = f1_score(y_test, y_pred_lr)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.9784735812133072
Precision: 0.9818913480885312
Recall: 0.9959183673469387
F1 Score: 0.9888551165146909


In [18]:
print(confusion_matrix(y_test, y_pred_lr))

[[ 12   9]
 [  2 488]]


### Random Forest

In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.metrics import accuracy_score

In [20]:
# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
# Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)
rf_pred = rf_model.predict(X_test_scaled)

rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)


print("Random Forest Accuracy:", rf_accuracy)
print("Precision:", rf_precision)
print("Recall:", rf_recall)
print("F1 Score:", rf_f1)

Random Forest Accuracy: 0.9784735812133072
Precision: 0.9799599198396793
Recall: 0.9979591836734694
F1 Score: 0.9888776541961577


In [22]:
print(confusion_matrix(y_test, rf_pred))

[[ 11  10]
 [  1 489]]


In [23]:
# K-Nearest Neighbors (KNN)
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)
knn_pred = knn_model.predict(X_test_scaled)

knn_accuracy = accuracy_score(y_test, knn_pred)
knn_precision = precision_score(y_test, knn_pred)
knn_recall = recall_score(y_test, knn_pred)
knn_f1 = f1_score(y_test, knn_pred)

print("KNN Accuracy:", knn_accuracy)
print("Precision:", knn_precision)
print("Recall:", knn_recall)
print("F1 Score:", knn_f1)


KNN Accuracy: 0.974559686888454
Precision: 0.9779559118236473
Recall: 0.9959183673469387
F1 Score: 0.9868554095045501


In [24]:
print(confusion_matrix(y_test, knn_pred))

[[ 10  11]
 [  2 488]]


In [25]:
# Naive Bayes
nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)
nb_pred = nb_model.predict(X_test_scaled)

nb_accuracy = accuracy_score(y_test, nb_pred)
nb_precision = precision_score(y_test, nb_pred)
nb_recall = recall_score(y_test, nb_pred)
nb_f1 = f1_score(y_test, nb_pred)
print("Naive Bayes Accuracy:", nb_accuracy)
print("Precision:", nb_precision)
print("Recall:", nb_recall)
print("F1 Score:", nb_f1)

Naive Bayes Accuracy: 0.9099804305283757
Precision: 0.9889867841409692
Recall: 0.9163265306122449
F1 Score: 0.951271186440678


In [26]:
print(confusion_matrix(y_test, nb_pred))

[[ 16   5]
 [ 41 449]]


In [27]:
# Support Vector Machine (SVM)
svm_model = SVC(kernel='linear')
svm_model.fit(X_train_scaled, y_train)
svm_pred = svm_model.predict(X_test_scaled)

svm_accuracy = accuracy_score(y_test, svm_pred)
svm_precision = precision_score(y_test, svm_pred)
svm_recall = recall_score(y_test, svm_pred)
svm_f1 = f1_score(y_test, svm_pred)
print("SVM Accuracy:", svm_accuracy)
print("Precision:", svm_precision)
print("Recall:", svm_recall)
print("F1 Score:", svm_f1)

SVM Accuracy: 0.9804305283757339
Precision: 0.98
Recall: 1.0
F1 Score: 0.98989898989899


In [28]:
print(confusion_matrix(y_test, svm_pred))

[[ 11  10]
 [  0 490]]


In [29]:
# XGBoost
xgb_model = xgb.XGBClassifier()
xgb_model.fit(X_train_scaled, y_train)
xgb_pred = xgb_model.predict(X_test_scaled)

xg_accuracy = accuracy_score(y_test, xgb_pred)
xg_precision = precision_score(y_test, xgb_pred)
xg_recall = recall_score(y_test, xgb_pred)
xg_f1 = f1_score(y_test, xgb_pred)
print("SVM Accuracy:", xg_accuracy)
print("Precision:", xg_precision)
print("Recall:", xg_recall)
print("F1 Score:", xg_f1)

SVM Accuracy: 0.9823874755381604
Precision: 0.9839034205231388
Recall: 0.9979591836734694
F1 Score: 0.9908814589665653


In [30]:
print(confusion_matrix(y_test, xgb_pred))

[[ 13   8]
 [  1 489]]
